# Generated by Django 4.2.5 on 2023-10-04 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='frist_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='phone_number',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
