# Generated by Django 4.1 on 2023-10-06 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_alter_tag_name_likedislike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedislike',
            name='user',
        ),
        migrations.AddField(
            model_name='likedislike',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_likedislike', to=settings.AUTH_USER_MODEL),
        ),
    ]
