# Generated by Django 4.2.5 on 2023-11-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_approval',
            field=models.BooleanField(default=False),
        ),
    ]
